server:
  port: 8000

# spring 配置
spring:
  application:
    name: gateway-server
  cloud:
    # nacos客户端配置
    nacos:
      # nacos服务注册与发现
      discovery:
        server-addr: 124.70.80.234:8844
        namespace: e034c7e8-68dd-4e68-a92a-c5dacee24c90
        # nacos服务配置
      config:
        server-addr: 124.70.80.234:8844
        namespace: e034c7e8-68dd-4e68-a92a-c5dacee24c90
        group: GATEWAY_GROUP
        file-extension: yaml

    # 网关配置
    gateway:
      discovery:
        locator:
          # 服务名小写
          lower-case-service-id: true


